const mongoose = require('mongoose');

const form16schema = mongoose.Schema({
    pan:String,
    finacialyear:String,
    regimetype:String,
    tanofemploye:String,
    organisation:String,
    typeoforganisation:String,
    salarysec171:String,
    salarysec172:String,
    lieusalarysec173:String,
    grossalary:String,
    allowancessectio:String,
    balance:String,
    standarDeduction:String,
    professionaltax:String,
    incomefromsalary:String,
    incomeonhouse:String,
    incomeothersource:String,
    c80:String,
    ccc80:String,
    ccd80:String,
    ccd801b:String,
    ccc80companycontriion:String,
    d80: String,
    dd80: String,
    ddb80: String,
    e80: String,
    ee80: String,
    u80: String,
    g80: String,
    gg80: String,
    tta80: String,
    totaldeduciton: String,
    reliefus89: String,
    totaltaxdeducted: String,
})

module.exports = form16schema;